## Array and it's basics
numpy

# Heading 1
## Heading 2
**bold**, *italic*, `code`



In [1]:
import numpy as np


In [51]:
my_1Darray = np.array([1, 4, 5, 3])
print("1D array:", my_1Darray)

my_2Darray = np.array([[0,12,2], [1,2,3]])
print("2D array:", my_2Darray)


1D array: [1 4 5 3]
2D array: [[ 0 12  2]
 [ 1  2  3]]


### List Vs Numpy array by using time

In [52]:
import time

In [53]:
start_time = time.time()

list_1 = [1, 2, 3, 4, 5]
lst_array = [i*2 for i in range(1000000)]
print(f"\n Time taken for list Operation time: {time.time() - start_time}")


np_array = np.arange(1000000) *2
print(f"\n Time taken for NumPy Operation time: {time.time() - start_time}")



 Time taken for list Operation time: 0.11953973770141602

 Time taken for NumPy Operation time: 0.12661147117614746


### Creating Array from Scratch

In [54]:
#Zeros Matix, Ones, full, random, 
np_array = np.zeros((5,5))
print('-->Zeros Matix:',np_array)  
np_array = np.ones((2,3))
print('-->Ones Matix:',np_array) 
np_array = np.full((3, 2), 7) 
print('-->Full Matix:',np_array)  
# np.random.randint(low, high, size)
np_array = np.random.randint(1, 10, size=(3,3))
print('-->Randiant Matix:',np_array)  
np_array = np.random.random((2,3))
print('-->Random Matix:',np_array)  
 

-->Zeros Matix: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
-->Ones Matix: [[1. 1. 1.]
 [1. 1. 1.]]
-->Full Matix: [[7 7]
 [7 7]
 [7 7]]
-->Randiant Matix: [[3 7 9]
 [9 5 6]
 [5 3 7]]
-->Random Matix: [[0.50167642 0.38624178 0.53694003]
 [0.31863233 0.37927407 0.39451851]]


### Vector, Matrix and Tensor 

In [55]:
#Properties of arrray

arr = np.array([[1, 2, 3], [1, 2, 5]])
print("Array:\n", arr)
print("Dimensions (ndim):", arr.ndim)       # 2
print("Shape:", arr.shape)                  # (2, 3)
print("Total Elements (size):", arr.size)   # 6
print("Data Type (dtype):", arr.dtype)      # int64 (or int32 depending on system)
print("Item Size (itemsize):", arr.itemsize)  # --> int64  →  64 bits  =  8 bytes (because 1 byte = 8 bits)
print("Total Bytes (nbytes):", arr.nbytes)    # 48 bytes (6×8)

# print("Shape",)

Array:
 [[1 2 3]
 [1 2 5]]
Dimensions (ndim): 2
Shape: (2, 3)
Total Elements (size): 6
Data Type (dtype): int64
Item Size (itemsize): 8
Total Bytes (nbytes): 48


### Array Reshaping


In [56]:
arr = np.arange(12)
print("Arrange:", arr)
'''a * b must equal the total number of elements.
   array.reshape(a, b) a-- rows and b--columns  '''
new_arr = arr.reshape(6,2)                           
print("Re",new_arr)
new1_arr = arr.reshape(3,-1)                           
print("--->Auto Dimension",new1_arr)

flattened = new_arr.flatten()
print("flattened:", flattened)

# Ravel 
Ravel = flattened.ravel()
print("Ravel:", Ravel)

arr = np.array([10, 20, 30, 40])
b = arr[::2]
print(b.base is arr)   # True → it's a view
b = arr.copy()
print(b.base is arr)   # False → it's a copy

view = arr[1:3]   # This is a view — no data is copied!
view[0] = 999     # Modify the view

print("Array :", arr)

Arrange: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Re [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
--->Auto Dimension [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
True
False
Array : [ 10 999  30  40]


## Phase Second
Basic Slicing, Sorting, filtering, fancing indexing and np.where(), Adding(Concatenate, Vstack and Hvstack) 
`Code`

In [ ]:
arr1D = np.arange(10)
arr2D = np.array([[1,2,3],
                  [3,4,5],
                  [4,56,67]])
print("Array 2D",arr2D)
print("Array 1D",arr1D)
#Slicing Indexing
print("Slicing of 1D Array ",arr1D[0:9:3])
print("Slicing of 2D Array ",arr2D[0,2]) #expected output 3
print("Slicing of 2D Array ",arr2D[2,1]) #expected output 56
print("Slicing of 2D Array--> ",arr2D[:,0:]) 
print("Slicing of 2D Array--> ",arr2D[:,0]) #expected output Entire Colunmn
print("Slicing of 2D Array ",arr2D[1]) #expected output Entire Row




Array 2D [[ 1  2  3]
 [ 3  4  5]
 [ 4 56 67]]
Array 1D [0 1 2 3 4 5 6 7 8 9]
Slicing of 1D Array  [0 3 6]
Slicing of 2D Array  3
Slicing of 2D Array  56
Slicing of 2D Array-->  [[ 1  2  3]
 [ 3  4  5]
 [ 4 56 67]]
Slicing of 2D Array-->  [1 3 4]
Slicing of 2D Array  [3 4 5]


### Sorting

In [58]:
unsorted = np.array([100,23,3,42,5,6,56])
print("Sorted Array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted Array By column:", np.sort(arr_2d_unsorted, axis=0))
print("Sorted Array By Row:", np.sort(arr_2d_unsorted, axis=1))


Sorted Array: [  3   5   6  23  42  56 100]
Sorted Array By column: [[1 1]
 [2 2]
 [3 3]]
Sorted Array By Row: [[1 3]
 [1 2]
 [2 3]]


### Filter

In [59]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)


Even numbers [ 2  4  6  8 10]


### Filter With Mask

In [60]:
arr = np.arange(10)
filter_data = arr[arr % 2 == 0] # arr[Condition]
filter_1data = arr[(arr > 3) & (arr % 2 == 0)] # use & (and), | (or), ~ (not) and always add parentheses
print("Filter Data :", filter_data)
print("Filter Data :", filter_1data)
# 2D 
M = np.array([[1,50],[2,40],[3,30],[4,20]])
rows = M[:,1] < 35         # look at 2nd column
print(rows)
M_filtered = M[M[:,1] < 35]
print(M_filtered)


Filter Data : [0 2 4 6 8]
Filter Data : [4 6 8]
[False False  True  True]
[[ 3 30]
 [ 4 20]]


### Fancy indexing vs np.where()

In [61]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where((numbers > 5)  & (numbers % 2 == 0))
print(where_result)
print("NP where", numbers[where_result])

condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)

[1 3 5]
(array([5, 7, 9]),)
NP where [ 6  8 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [4]:
ids = np.array([101,102,103,104])
keep = np.isin(ids, [101,102])
print(ids[keep])                   # [101,104]


[101 102]


### Adding and removing data

In [63]:
original_arr = np.array([1,23,3])
new_arr = np.array([11,23,30])
add = np.concatenate((original_arr, new_arr))
print("Adding to arrays in Numpy:", add)
def sorted(a):
    sorted_array = np.sort(a)
    print("Sorted array after Concatenate:",sorted_array)
sorted(add)    

Adding to arrays in Numpy: [ 1 23  3 11 23 30]
Sorted array after Concatenate: [ 1  3 11 23 23 30]


### array compatibilty

In [64]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [65]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
With new column [[1 2 7]
 [3 4 8]]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr[:4], 1)
print("Array after deletion: ", deleted)

Array after deletion:  [1 3 4]
